Alt+RIGHT no-osd cycle-values video-rotate "90" "180" "270" "0"
Alt+LEFT no-osd cycle-values video-rotate "270" "180" "90" "0"

# 방향키 탐색 시 키프레임 단위로 즉시 이동
RIGHT seek  5 exact
LEFT  seek -5 exact

# Shift + 방향키는 가장 가까운 키프레임으로 순간 이동
Shift+RIGHT seek  5 keyframes
Shift+LEFT  seek -5 keyframes

